config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :plans do
    resources :features
  end

  resources :users do
    resources :plans, shallow: true
  end

  resources :users do
    resources :subscriptions, shallow: true do
      member do
        get :charge_user
      end
    end
  end

  resources :plans do
    resources :subscriptions
  end
  resources :subscriptions do
    resources :transactions, shallow: true
  end
  resources :subscriptions do
    resources :usages, shallow: true
  end

  get 'all_subscriptions', to: 'subscriptions#home'
  get 'all_subs', to: 'usages#all_subs'
  get 'all_usages', to: 'usages#home'
  root to: 'welcome#index'
  get '*path' => redirect('/')
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Welcome controller
class WelcomeController < ApplicationController
	skip_before_action :authenticate_user!
 def index
   @user = current_user
   @plans = Plan.all
   @subscriptions = @user.subscriptions.all if @user
 end
end

app/views/welcome/index.html.erb
<h1 class="jumbotron text-center"> welcome to billing and recurring app in rails </h1>
<% if user_signed_in? %>
	<%if policy(@user).admin? %>
	<center>
		<%=link_to 'View subscriptions', all_subscriptions_path, :class=> "btn btn-primary btn-lg", :role=> "button"%>
		<%=link_to 'View usages', all_subs_path, :class=> "btn btn-primary btn-lg", :role=> "button"%>
		<%=link_to 'Add New plan', new_plan_path, :class=> "btn btn-primary btn-lg", :role=> "button"%><br /><br /><br />
		    <%=render 'plans/plans', plans: @plans%> 
		<%end%>
	</center>
	
	<% if policy(@user).buyer? %>
		<center>
			<% if @subscriptions.any? %>
			<%=link_to 'My subscriptions', user_subscriptions_path(current_user), :class=> "btn btn-primary btn-lg", :role=> "button"%>
			<%end%>
			<h1>Here are the plans for you </h1>
			<%=render 'plans/plans', plans: @plans%>
		</center>
	<%end%>
<%else%>
	<div class="col-md-12 text-center" style="margin-top: 250px">
		<%=link_to 'Login', new_user_session_path, :class=> "btn btn-primary btn-lg", :role=> "button"%>
		<%=link_to 'Sign up', new_user_registration_path, :class=> "btn btn-primary btn-lg", :role=> "button"%>
<%end%>