config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :plans do
    resources :features
  end

  resources :users do
    resources :plans, shallow: true
  end

  resources :users do
    resources :subscriptions, shallow: true do
      member do
        get :charge_user
      end
    end
  end

  resources :plans do
    resources :subscriptions
  end
  resources :subscriptions do
    resources :transactions, shallow: true
  end
  resources :subscriptions do
    resources :usages, shallow: true
  end

  get 'all_subscriptions', to: 'subscriptions#home'
  get 'all_subs', to: 'usages#all_subs'
  get 'all_usages', to: 'usages#home'
  root to: 'welcome#index'
  get '*path' => redirect('/')
end

app/models/usage.rb
# frozen_string_literal: true

# usage model
class Usage < ApplicationRecord
  belongs_to :user
  belongs_to :plan
  belongs_to :subscription
  belongs_to :feature
end

app/controllers/usages_controller.rb
# frozen_string_literal: true

# Usage controller
class UsagesController < ApplicationController
  before_action :set_usage, only: %i[edit update]
  before_action :set_subscription, only: %i[index new create]
  before_action :set_usage_to_create, only: %i[create]

  def index
    @usages = @subscription.usages.all
    authorize @usages
  end

  def all_subs
    @subscriptions = Subscription.all
    authorize @subscriptions
  end

  def new
    @usage = @subscription.usages.new
    authorize @usage
  end

  def create
    if @usage.save
      authorize @usage
      redirect_to root_url
    else
      render :new
    end
  rescue ActiveRecord::RecordNotUnique
    flash[:danger] = 'you cannot add usage of already added feature'
    redirect_to subscription_usages_path(@subscription)
  end

  def home
    @usages = Usage.all
  end

  def edit
    @usage = Usage.find(params[:id])
    authorize @usage
  end

  def update
    if @usage.update(usage_params)
      authorize @usage
      flash[:notice] = 'Usage updated successfully'
      redirect_to root_url
    else
      render :edit
    end
  end

  private

  def set_usage
    @usage = Usage.find(params[:id])
  end

  def set_usage_to_create
    @usage = @subscription.usages.new(usage_params)
    @usage.plan = @subscription.plan
    @usage.user = @subscription.user
    @usage.subscription = @subscription
  end

  def set_subscription
    @subscription = Subscription.find(params[:subscription_id])
  end

  def usage_params
    params.require(:usage).permit(:units_count, :feature_id)
  end
end

app/helpers/usage_helper.rb
# frozen_string_literal: true

# UsageHelper
module UsageHelper
  def specific_features(subscription)
    subscription.plan.features.map { |f| [f.name, f.id] }
  end
end

app/views/usages/_form.html.erb
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <%= form_with(model: [@subscription, @usage], local: true) do |form| %>
        <% if @usage.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@usage.errors.count, "error") %> prohibited this usage from adding to database:</h2>
            <ul>
            <% @usage.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <div class="field">
          <%if @usage.feature %>
            <%= form.label :Select_feature %>
              <%= form.text_field :Select_feature, value: @usage.feature.name, class: "form-control ",  :disabled=> true%>
            </div>
          <%else%>
          <div class="form-group">
              <%= form.label :Select_feature %></br>
              <%= form.select :feature_id, options_for_select(specific_features(@subscription)), {}, class: 'form-control',prompt: 'Select_feature' %>
          </div>
          <%end%>
          <div class="field">
            <%= form.label :units_count %>
            <%= form.number_field :units_count, class: "form-control" %>
          </div>
        </div>
        <div class="actions text-center mt-3">
          <%= form.submit usage_text, class:"btn btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>

app/views/usages/all_subs.html.erb
<center>
  <h1 style="margin-top: 30px">Listing all subscriptions of all users</h1>
</center>
<div class="container" style="margin-top: 110px">
  <div class="row">
    <table class="table table-striped table-bordered table-responsive-md">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Plan ID</th>
          <th scope="col">User ID</th>
          <th scope="col">Billing day</th>
          <th scope="col">Plan Fees</th>
          <th scope="col">Charge users</th>
        </tr>
      </thead>
      <tbody>
        <% @subscriptions.each do |subscription| %>
          <tr>
            <td><%=subscription.plan_id%></td>
            <td><%=subscription.user_id%></td>
            <td><%=subscription.bill_day%></td>
            <td><%=subscription.plan.fee%></td>
              <td><%=link_to 'Add Usage', subscription_usages_path(subscription), :class=> "btn btn-primary d-flex justify-content-center", :role=> "button"%></td> 
          </tr>
          <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/usages/edit.html.erb
<h1 class="text-center">Edit usage</h1>
<%= render partial:'form', subscription: @subscription ,usage: @usage, locals: {usage_text: "Edit Usage"} %>
	

app/views/usages/home.html.erb
<center>
  <h1 style="margin-top: 30px">Listing all subscriptions of all users</h1>
</center>
<div class="container" style="margin-top: 110px">
  <div class="row">
    <table class="table table-striped table-bordered table-responsive-md">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Plan ID</th>
          <th scope="col">User ID</th>
          <th scope="col">Subscription ID</th>
          <th scope="col">Plan Fees</th>
          <th scope="col">Charge users</th>
        </tr>
      </thead>
      <tbody>
        <% @usages.each do |usage| %>
          <tr>
            <td><%=usage.plan.name%></td>
            <td><%=usage.user.name%></td>
            <td><%=usage.subscription_id%></td>
            <td><%=usage.plan.fee%></td>
              <td><%=link_to 'Add units', new_subscription_usage_path(usage.subscription), :class=> "btn btn-primary d-flex justify-content-center", :role=> "button"%></td> 
          </tr>
          <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/usages/index.html.erb
<center>
  <h1 style="margin-top: 30px">Listing all usages of subscription ID <%=@subscription.id %> </h1>
  <td><%=link_to 'Add units', new_subscription_usage_path(@subscription), :class=> "btn btn-primary btn-lg justify-content-center", :role=> "button"%></td>
</center>
<% if @usages.any?%>
  <div class="container" style="margin-top: 110px">
    <div class="row">
      <table class="table table-striped table-bordered table-responsive-md">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Plan Name</th>
            <th scope="col">User Name</th>
            <th scope="col">Feature Name</th>
            <th scope="col">Plan Fees</th>
            <th scope="col">Units</th>
            <th scope="col">Edit Units</th>
          </tr>
        </thead>
        <tbody>
          <% @usages.each do |usage| %>
            <tr>
              <td><%=usage.plan.name%></td>
              <td><%=usage.user.name%></td>
              <td><%=usage.feature.name%></td>
              <td><%=usage.plan.fee%></td>
              <td><%=usage.units_count%></td>
                <td><%=link_to 'Edit units', edit_usage_path(usage), :class=> "btn btn-primary d-flex justify-content-center", :role=> "button"%></td> 
            </tr>
            <%end%>
        </tbody>
      </table>
    </div>
  </div>
<%else%>
<h1 class="text-center" style="margin-top: 150px">No usages so far</h1>
<%end%>

app/views/usages/new.html.erb
<center>
	<h1>Add usage</h1>
</center>
	<%= render partial:'form', subscription: @subscription ,usage: @usage, locals: {usage_text: "Add usage"} %>

app/views/usages/show.html.erb
<h1>usage updated</h1>