config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :plans do
    resources :features
  end

  resources :users do
    resources :plans, shallow: true
  end

  resources :users do
    resources :subscriptions, shallow: true do
      member do
        get :charge_user
      end
    end
  end

  resources :plans do
    resources :subscriptions
  end
  resources :subscriptions do
    resources :transactions, shallow: true
  end
  resources :subscriptions do
    resources :usages, shallow: true
  end

  get 'all_subscriptions', to: 'subscriptions#home'
  get 'all_subs', to: 'usages#all_subs'
  get 'all_usages', to: 'usages#home'
  root to: 'welcome#index'
  get '*path' => redirect('/')
end

app/models/subscription.rb
# frozen_string_literal: true

# Subscription model
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :plan
  has_many   :usages, dependent: :destroy
  has_many   :transactions
  validates  :bill_day, inclusion: 1..28

  def calculate_payment(subscription, _features, plan)
    plan_fee = plan.fee
    usages = subscription.usages.all
    usages.each do |usage|
      if usage.units_count > usage.feature.max_unit_limit
      	plan_fee += (usage.feature.unit_price * (usage.units_count - usage.feature.max_unit_limit))
	     else
	       plan_fee
	     end
    end
  end
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

# Subscription controller
class SubscriptionsController < ApplicationController
  before_action :set_user, only: %i[create]
  before_action :set_charge_user, only: %i[charge_user]
  before_action :set_create, only: %i[create]
  before_action :set_transaction, only: %i[charge_user]

  def index
    @subscriptions = policy_scope(Subscription)
    @plan = @subscriptions.first.plan if @subscriptions.any?
  end

  def new
    @plan = Plan.find(params[:plan_id])
    @subscription = Subscription.new
  end

  def home
    @subscriptions = Subscription.all.sort_by { |sub| sub.bill_day == Time.zone.today.strftime('%d').to_i ? 0 : 1 }
    authorize @subscriptions.first if @subscriptions.any?
  end

  def create
    if @subscription.save
      flash[:notice] = 'Subscription done successfully'
      redirect_to root_url
    else
      flash.now[:notice] = 'OOPS.. Subscription is not done successfully'
      render :new
    end
  end

  def show
    @user = User.first
    @subscriptions = Subscription.all
    @plan = @subscriptions.first.plan
  end

  def charge_user
    if @transaction.save
      send_charge_mail(@user, @transaction, @plan, @feature)
      flash[:notice] = 'User is charged successfully'
      redirect_to all_subscriptions_path
    else
      flash[:danger] = 'User is not charged successfully'
      redirect_to root_url
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:plan_id, :bill_day)
  end

  def set_charge_user
    @subscription = Subscription.find(params[:id])
    @user = @subscription.user
    @plan = Plan.find(@subscription.plan_id)
  end

  def set_create
    @plan = Plan.find(params[:subscription][:plan_id])
    @subscription = Subscription.new(subscription_params)
    @subscription.user = @user
  end

  def set_transaction
    @transaction = Transaction.new(user_id: @user.id, subscription_id: @subscription.id,
                                   total_charges: @subscription.calculate_payment(@subscription, @features, @plan))
  end

  def set_user
    @user = current_user
  end

  def send_charge_mail(user, transaction, plan, feature)
    UserMailer.charge_user(user: user, transaction: transaction, plan: plan,
                           feature: feature).deliver_later
  end

  def usage_params
    params.require(:subscription).permit(:plan_id)
  end
end

app/views/subscriptions/_form.html.erb
<div class="container">
  <div class="col-md-4 col-md-offset-4">
    <%= form_with(model: @subscription, local: true) do |form| %>
  <% if @subscription.errors.any? %>
      <div id="error_explanation">
          <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
          <ul>
          <% subscription.errors.full_messages.each do |message| %>
            <li>billday can't be empty, greater than 28 and less than 1</li>
          <% end %>
          </ul>
      </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= form.hidden_field :plan_id, value: @plan.id, class: "form-control" %>
    </div>
    <div class="field">
      <%= form.label :bill_day %>
      <%= form.text_field :bill_day, autofocus: true,class: "form-control" %>
    </div>
  </div>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>
  </div>
</div>

app/views/subscriptions/home.html.erb
<center>
	<h1 style="margin-top: 30px">Listing all subscriptions of all users</h1>
</center>
<div class="container" style="margin-top: 110px">
	<div class="row">
		<table class="table table-striped table-bordered table-responsive-md">
		  <thead class="thead-dark">
		    <tr>
		      <th scope="col">Plan ID</th>
		      <th scope="col">User ID</th>
		      <th scope="col">Billing day</th>
		      <th scope="col">Plan Fees</th>
		      <th scope="col">Charge users</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @subscriptions.each do |subscription| %>
			    <tr>
			      <td><%=subscription.plan_id%></td>
			      <td><%=subscription.user_id%></td>
			      <td><%=subscription.bill_day%></td>
			      <td><%=subscription.plan.fee%></td>
			      <%if subscription.transactions.any? %>
		      	   <td><a href="#" class="btn btn-primary d-flex justify-content-center disabled" role="button" aria-pressed="true">Already Charged</a></td>
			      <%elsif (subscription.bill_day) == (Date.today.strftime("%d").to_i)%>
			      	<td><%=link_to 'Charge User', charge_user_subscription_path(subscription), :class=> "btn btn-primary d-flex justify-content-center", :role=> "button"%></td>
			      	
		   		 <%else%>
		   		 	<td>Wait to charge</td>
		   		 <%end%>	
		   		</tr>
		   		<%end%>
			</tbody>
		</table>
	</div>
</div>

app/views/subscriptions/index.html.erb
<div class="container">
  <center>
    <%if @subscriptions.any? %>
    <h1>Listing All Subscriptions of <%= current_user.name %> </h1>
    <table class="table">
      <tr>
        <th>Plan ID</th>
        <th>Plan Name</th>
        <th>Plan Fee</th>
        <th>User Name </th>
        <th>Features</th>
        <th>Subscribed on</th>

      </tr> 
        <% @subscriptions.each do |subscription| %> 
              <tr>
              <td><%= subscription.plan_id %></td>
              <td><%= subscription.plan.name %></td>
              <td><%= subscription.plan.fee %></td>
              <td><%= subscription.user.name %></td>
              <td><%=link_to 'Click here', plan_features_path(subscription.plan)%></td>
              <td><%=subscription.created_at.strftime("%d %B %Y")%></td>
              <td style="color: lightgrey">(subscribed <%=Date.today.mjd - subscription.created_at.to_date.mjd%> days ago)</td>
            </tr>
        <%end%>
    </table>
    <%else%>
        <h1 style="margin-top: 200px">You have no subscriptions</h1>
        
        <h5>Click <%=link_to 'here', user_session_path%> to go back</h5>
      <%end%>
    <br>
  </center>
</div>

app/views/subscriptions/new.html.erb
<center>
  <h1>New Subscription</h1>
</center>
  <%= render 'form', subscription: @subscription %>

app/views/subscriptions/show.html.erb
<% @plan.subscriptions.each do |subscription| %>
  <p>
    <strong>User ID:</strong>
    <%= subscription.user_id %>
  </p>
  <p>
    <strong>Plan ID:</strong>
    <%= subscription.plan_id %>
  </p>
<% end %>