config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :plans do
    resources :features
  end

  resources :users do
    resources :plans, shallow: true
  end

  resources :users do
    resources :subscriptions, shallow: true do
      member do
        get :charge_user
      end
    end
  end

  resources :plans do
    resources :subscriptions
  end
  resources :subscriptions do
    resources :transactions, shallow: true
  end
  resources :subscriptions do
    resources :usages, shallow: true
  end

  get 'all_subscriptions', to: 'subscriptions#home'
  get 'all_subs', to: 'usages#all_subs'
  get 'all_usages', to: 'usages#home'
  root to: 'welcome#index'
  get '*path' => redirect('/')
end

app/models/plan.rb
# frozen_string_literal: true

# Plan model
class Plan < ApplicationRecord
  has_many :features, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :fee, presence: true
end

app/controllers/plans_controller.rb
# frozen_string_literal: true

# Plans controller
class PlansController < ApplicationController
  before_action :set_plan, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    @plans = Plan.all
    flash.now[:notice] = "We have exactly #{@plans.size} plans available."
  end

  def new
    @plan = Plan.new
    authorize @plan
  end

  def create
    @plan = Plan.new(plan_params)
    authorize @plan
    if @plan.save
      flash[:alert] = 'Plan is created successfully'
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @user = current_user
    authorize @plan
  end

  def update
    authorize @plan
    if @plan.update(plan_params)
      flash[:alert] = 'Plan is updated successfully'
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
    authorize @plan
    @plan.destroy
    flash[:destroy] = 'Plan is destroyed successfully'
    redirect_to root_url
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:name, :fee)
  end
end

app/helpers/plans_helper.rb
# frozen_string_literal: true

# PlansHelper
module PlansHelper
  def subscribed?(plan)
    subscriptions.find_by(plan_id: plan.id)
  end
end

app/views/plans/_form.html.erb
<div class="container text-center">
  <div class="form" style="margin-left:100px;width: 70%;text-align: center;">
    <%= form_with(model: @plan, local: true) do |form| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group new_user">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group new_user">
    <div class="field">
      <%= form.label :fee %>
      <%= form.number_field :fee, class: "form-control" %>
    </div>
  </div>

  <div class="actions new_user">
    <%= form.submit textt, class:"btn btn-primary"%>
  </div>
<% end %>
  </div>
</div>

app/views/plans/_plans.html.erb
<div class="row">
  <% @plans.each do |plan| %>
    <div class="col-sm-4 mt-2">

        <div class='card text-center'>
          <div class='card-header'>
            Plan
            <div class="float-right">
              <% if policy(@user).admin? %>
                <%= link_to fa_icon('edit'), edit_plan_path(plan), class: 'text-dark', title: 'Edit Plan' %>
              <% end %>
              <% if policy(@user).admin? %>
                <%= link_to fa_icon('trash'), plan, method: :delete, data: { confirm: 'Are you sure you want to delete this plan?' }, class: 'text-danger ml-3', title: 'Delete Plan' %>
              <% end %>
            </div>
          </div>
          <div class='card-body'>
            <h5 class='card-title'><%= plan.name %></h5>
            <p class='card-text'>
              Plan Fee: <b><%= plan.fee %></b>
            </p>
            <%if plan.features.any?%>
              <p class='card-text'> <%= link_to 'Show features', plan_features_path(plan) %></br></p>
            <%else%>
                <p><b>OOPS.. No features so far</b></p>
            <%end%>
            <% if policy(@user).admin? %>
              <%= link_to 'Add features', new_plan_feature_path(plan) %></br>
            <%elsif policy(@user).buyer? %>
              <% if @subscriptions.find_by(plan_id:plan.id) %>
                <a href="#" class="btn btn-primary disabled" role="button" aria-pressed="true">Subscribed</a>
              <%elsif plan.features.any? %>
                  <%=link_to 'Subscribe',
                    new_plan_subscription_path(plan),
                    class: 'btn btn-primary btn-lg',
                    role: "button"
                  %> 
              <%else%>
                <a href="#" class="btn btn-primary disabled" role="button" aria-pressed="true">Wait for features to subscribe</a>         
              <%end%>
            <%end%>
          </div>
          <div class='card-footer text-muted d-block text-center'>
            <%= plan.created_at.strftime('%d-%m-%Y %I:%M %p') %>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/plans/edit.html.erb
<%= render partial:'form', plan: @plan, locals: {textt: "Update Plan"}%>

app/views/plans/index.html.erb
<center>
  <h1>Plans</h1>
  <% if current_user.admin? %>
    <%= link_to 'Add New Plan', new_plan_path %>
  <%end%>
</center>
<div class="container">
  <div class="row">
  <% @plans.each do |plan| %>
  <div class="card text-center col-sm-4" style="margin-right: 30px; margin-bottom: 30px">
  <div class="card-body">
      <h5 class="card-title">Plan Name: <%=plan.name%></h5>
      <p class="card-text">Plan Fee: <%=plan.fee%></p>
      <td><%= link_to 'Show Details', plan %></td></br>
      <%if plan.features.any?%>
          <%= link_to 'Show features', plan_features_path(plan) %></br>
      <%else%>
          <h5>OOPS.. No features so far</h5>
      <%end%>
      <% if current_user.admin?%>
          <%= link_to 'Add features', new_plan_feature_path(plan) %></br>
          <%= link_to 'Change plan details', edit_plan_path(plan) %></td></br>
          <%= link_to 'Delete Plan', plan, method: :get, data: { confirm: 'Are you sure to delete this plan?' } %>
      <%end%>
    </div>
  </div>
    <% end %>
</div>
</div>

app/views/plans/new.html.erb
<h1 class="text-center">Add Plan</h1>
<%= render partial:'form', plan: @Plan, locals: {textt: "New Plan"}%>

app/views/plans/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @plan.fee %>
</p>


<%= link_to 'Edit', edit_plan_path(@plan) %>